### ISSUE TITLE
Scrollbar space reserved when there's no scrollbar

### ISSUE THREAD

**Issue by sywesk** [react-component/dialog#130]
Hello dear maintainer,

Following a recent commit from 8-9 days ago, that changed the behavior of / refactored the scrolling effect on the Dialog component, I now always get a 17px padding on my body element when I open a dialog (which is the size estimated by some scrollbar rc-util script code), ignoring the presence of the scrollbar. 

I reproduced on edge dev / chromium. This problem appeared today for me, just after updating my dependencies to avoid some npm audit problems.

If this may help, i'm using ant-design 3.20.4, which uses the dialog component behind its Modal implmentation. 
The commit: https://github.com/react-component/dialog/commit/f6cb31a3b9e86bc419a5cbe25be7769ed8a156fd

If you need any other detail, configuration, version, code, etc, do not hesitate to ask me about it. 
As a workaround, i reverted to antd 3.20.3, which depends on the 7.4.1 version of this lib.

Thank you,
Benjamin

**Comment by jljsj33** [comment]
fix
