### ISSUE TITLE
How Dialog re-align when width change?

### ISSUE THREAD

**Issue by kohver** [react-component/dialog#15]
Hi! May be there is something that I want to know, but I don't understand Chinese :sweat_smile:  https://github.com/react-component/dialog/issues/11

The question is when I have tree like this:
```js
<Parent>
  <Child />
</Parent>
```
and `Child` component changes its state, `Parent` component does not handle this event, because `componentDidUpdate` does not called and as a result can't re-align itself.
I looked at `Align`, `DOMWrap` and `DialogWrap` components, but still can't figure out how do you do this magic.

Thanks!

**Comment by MarshallChen** [comment]
The 'magic' is here I think. https://github.com/react-component/align/blob/master/src/Align.jsx#L76

**Comment by yiminghe** [comment]
will use css in 6.0
