### ISSUE TITLE
添加类似maskClosable的prop，配置点击mask是否关闭dialog

### ISSUE THREAD

**Issue by paseo** [react-component/dialog#16]
组件对点击右上角关闭和点击mask遮罩关闭没有区分差异。
使用过程中有用户反映，容易误点到遮罩导致dialog意外关闭。
是否可以提供类似maskClosable之类的配置项，禁用mask遮罩的关闭按钮，或者在onClose回调里给相应参数来区分是哪部分引起的关闭？

**Comment by afc163** [comment]
https://github.com/react-component/dialog/pull/14

**Comment by paseo** [comment]
#17
