### ISSUE TITLE
为什么 DialogWrap unmount 的时候还要再去检查 visiable 并 render 一次 Dialog？

### ISSUE THREAD

**Issue by yesmeck** [react-component/dialog#18]
这里 https://github.com/react-component/dialog/blob/master/src%2FDialogWrap.jsx#L53-L58

我想自己去 unmount `DialogWrap`（不改变 visible），但是发现这里如果`visible: true`的会再次 render `Dialog`，这时如果在`DialogWrap`的 children 里有用 `ref`的话 react 就会报错。

例子：http://codepen.io/yesmeck/pen/ONRvrz?editors=0010

打开 modal 后点击关闭就会报错。

**Comment by yesmeck** [comment]
同样的问题 https://github.com/ant-design/ant-design/issues/935

**Comment by yesmeck** [comment]
我知道了，是为了显示关闭动画吧。但是这样的话在使用`react-router`的情况下，在`Dialog`显示的时候改变路由，也会出错吧。

**Comment by yiminghe** [comment]
https://github.com/facebook/react/pull/6095

用 ref  function

**Comment by yesmeck** [comment]
但是在用`react-router`的情况下就没办法用`ref`手动  unmount 了吧。

**Comment by yesmeck** [comment]
但是在用`react-router`的情况下就没办法用`ref`手动  unmount 了吧。

**Comment by yiminghe** [comment]
试下 这种，没问题的

```
ref={(c) => {this.c=c}}
```

**Comment by yesmeck** [comment]
嗯，这样没问题了
