### ISSUE TITLE
Support destroyOnHide

### ISSUE THREAD

**Issue by aight8** [react-component/dialog#22]
rc-trigger support this, but I want to use rc-dialog as standalone component for errors. So it were nice when this option were possible on rc-dialog level already.

**Comment by yiminghe** [comment]
Just render null

http://react-component.github.io/dialog/examples/ant-design.html

**Comment by yesmeck** [comment]
@afc163 可以考虑加这个，一来解决 React 16 render null 的时候会没动画，二来 Modal 内部的组件可以比较方便的使用生命周期。

**Comment by afc163** [comment]
对，Modal 清空数据是老大难问题

**Comment by yesmeck** [comment]
Trace in https://github.com/ant-design/ant-design/issues/8494
