### ISSUE TITLE
prefixCls 支持自定义

### ISSUE THREAD

**Issue by mumiao** [react-component/dialog#223]
![image](https://user-images.githubusercontent.com/22880945/103194891-f6e3c900-491b-11eb-9692-abea46e22d22.png)

**Comment by yoyo837** [comment]
没太明白什么意思

**Comment by mumiao** [comment]
我有项目依赖了**Rc-Dialog** 采用了BEM组件布局 
eg：
![image](https://user-images.githubusercontent.com/22880945/103196171-a15ceb80-491e-11eb-9f67-a2c2aba5123b.png)
其中需要对 **Rc-Dialog**部分样式需要重写
eg：
![image](https://user-images.githubusercontent.com/22880945/103196219-ba659c80-491e-11eb-9d14-7eaa5f39cf04.png)
如上 也需要遵循 **BEM**布局
` &__mask {
        &--hidden {
        }
   }

  &__wrap {

  }

 &__content {
 }

&__header {
}
`
目标是将  ’-‘  作为props传进去，比如 modifier：’-‘ | ’__' | '--'
![image](https://user-images.githubusercontent.com/22880945/103196812-d74e9f80-491f-11eb-804e-9b4c2f76e104.png)

**Comment by yoyo837** [comment]
覆盖不了className吗？

**Comment by yoyo837** [comment]
目前看来，要么你BEM的样式额外加一个`-`链接的来兼容，要么PR改掉所有需要支持直接传入className的地方

**Comment by mumiao** [comment]
> 覆盖不了className吗？

![image](https://user-images.githubusercontent.com/22880945/103197147-7b384b00-4920-11eb-940a-8f92bfcfa5b0.png)
classname覆盖只支持wrapper层的
Dialog组件的基本结构 mask wrap content header 不支持重写classname

**Comment by yoyo837** [comment]
层级覆盖一下呢？
.wrapper .xxxx-body {
}

**Comment by mumiao** [comment]
> 目前看来，要么你BEM的样式额外加一个`-`链接的来兼容，要么PR改掉所有需要支持直接传入className的地方

- BEM的样式额外加一个`-`链接的来兼容目前是这么做的；层级覆盖可行，违背了BEM初衷
- PR改掉所有需要支持直接传入className的地方
   有个地方要探讨下，我是将  newPrefixCls = （prefixCls + 连接符 ）eg：`${perfixCls-body}`  将 `${perfixCls}-`作为默认prefix
  还是支持className覆盖些。
   
  直接重写prefix把连接符带着，会涉及antd版本很多地方改动。而且为了统一 其他组件也需要跟上。太不合理我感觉
  要么就支持 className覆盖。这样只改动RC-Dialog。就是改的地方稍微多了一些。

- 

>

**Comment by mumiao** [comment]
直接将连字符作为props更不合理。需要多次切断 className的拼接

**Comment by yoyo837** [comment]
你理想的情况认为dialog应该怎样改？

**Comment by kerm1it** [comment]
依赖了 rc-dialog 后，如果要覆盖组件的样式，肯定就需要按照 rc-dialog 自己的类名来覆盖，而不是让第三方组件去适应业务的命名规则。

自己的业务使用 BEM 规范这是没有问题的，没有必要为了符合BEM规范去做这些修改。

如果你还使用了其他的UI组件库，它们肯定也会存在一些内部类名命名，如果你想覆盖样式，不可能让它们也作出修改。

**Comment by mumiao** [comment]
> 依赖了 rc-dialog 后，如果要覆盖组件的样式，肯定就需要按照 rc-dialog 自己的类名来覆盖，而不是让第三方组件去适应业务的命名规则。
> 
> 自己的业务使用 BEM 规范这是没有问题的，没有必要为了符合BEM规范去做这些修改。
> 
> 如果你还使用了其他的UI组件库，它们肯定也会存在一些内部类名命名，如果你想覆盖样式，不可能让它们也作出修改。

可是有些css命名不希望用前缀 '-' 来分隔 也只能覆盖么。

**Comment by mumiao** [comment]
> 你理想的情况认为dialog应该怎样改？

采用第二种方案

**Comment by mumiao** [comment]
@afc163

**Comment by kerm1it** [comment]
像 header、title、content 这些部分的类名，本来就没有提供对应的 API 去自定义类名覆盖样式。

所以你要的 API 应该是自定义 header、title、content 这些部分的 className。

**Comment by mumiao** [comment]
> @afc163
我更倾向于自定义 prefix；你说的这种可以作为替代方案。如果确定方案。我就着手补充单测提pr了。

**Comment by kerm1it** [comment]
你艾特错人了😂

**Comment by kerm1it** [comment]
自定义 prefix 本身的适用性不广，可能加了后只有你自己能用到。

**Comment by mumiao** [comment]
> 自定义 prefix 本身的适用性不广，可能加了后只有你自己能用到。

那我能提pr么  我觉得我这个确实是个场景

**Comment by kerm1it** [comment]
可以，支持 header、title、content 这些部分自定义类名即可，不需要自定义 `prefixCls`

**Comment by mumiao** [comment]
> 可以，支持 header、title、content 这些部分自定义类名即可，不需要自定义 `prefixCls`

thax,  i will prefix

**Comment by mumiao** [comment]
> 可以，支持 header、title、content 这些部分自定义类名即可，不需要自定义 `prefixCls`

header title content 
推荐哪种方案？

-  单独命名 headerClassName titleclassName 比较好

- `classNames: {

        headerClassName,
        titleClassName,
        contentClassName
 }
`

**Comment by kerm1it** [comment]
单独命名就行，不用合在一起，本身还有 className
