### ISSUE TITLE
dialog 浮层定位太靠页面底部

### ISSUE THREAD

**Issue by kasinooya** [react-component/dialog#25]
提问：dialog 怎么老是顶着页面底部，和顶部留出那么大块空余呢

![img](https://os.alipayobjects.com/rmsportal/QfAyxwabdvTapDt.png)

**Comment by afc163** [comment]
http://ant.design/components/modal/#api 

align

**Comment by kasinooya** [comment]
缺少 align 写法的例子

**Comment by kasinooya** [comment]
补上范例，居中样式：
```
align: { points: ['cc', 'cc'] }
```
