### ISSUE TITLE
Children context not passed down to the children of dialog component

### ISSUE THREAD

**Issue by aight8** [react-component/dialog#27]
I created a wrapper around the dialog component to setup a custom dialog with some extra functionality. One of it's functionality should be to provide a context with some functions to the dialogs children, which can set the title from inside. But when I create a child context in my wrapper it's not passed to the children. Any idea for a solution for this?

**Comment by yiminghe** [comment]
should pass context by https://github.com/react-component/dialog/blob/master/src/DialogWrap.jsx#L55

need demo
