### ISSUE TITLE
Error: "export 'useId' (imported as 'React') was not found in 'react'"after upgrading to v8.8.1

### ISSUE THREAD

**Issue by zhangminggeek** [react-component/dialog#289]
devScripts.js:3141 export 'useId' (imported as 'React') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

**Comment by karthik-hr** [comment]
Facing same problem

**Comment by zhangminggeek** [comment]
> Facing same problem

https://github.com/react-component/util/pull/300
