### ISSUE TITLE
Dialog causes body to have an unwanted padding-right 

### ISSUE THREAD

**Issue by tarkanlar** [react-component/dialog#33]
Dialog causes body to have an unwanted padding right, probably because it should remove scrollbar but it doesnt.

**Comment by yiminghe** [comment]
if body has scrollbars, then when dialog show, it will set body to overflow hidden and give a padding to prevent content jitter

**Comment by paradite** [comment]
In my case, for some reason the overflow detection was not working correctly in the first 200-500ms of app load (delay modal show and the padding won't appear). Manually adding some css to `body` solved the issue:

```
body {
  overflow: hidden;
}
```
