### ISSUE TITLE
6.5.2版本 onMouseDown 事件连续触发

### ISSUE THREAD

**Issue by deot** [react-component/dialog#42]
6.5.2存在这个问题，导致我的Picker组件一出来就关闭了；

antd-mobile的版本没做好它引用其他组件的版本；

最主要的原因是和与[react-fastclick](https://github.com/JakeSidSmith/react-fastclick)造成了冲突，它修改了对React.createElement的引用；

**Comment by warmhug** [comment]
@yiminghe 
在安卓上（或 mac Chrome 切换到 Nexus 等 Android ua） antd-mobile 的 modal 、picker、date-picker 组件，都是这种问题，刚显出来就自动关闭，如图：
![gg](https://cloud.githubusercontent.com/assets/2011119/20967945/c4846c0c-bcbc-11e6-9d92-8832e2fc8973.gif)
