### ISSUE TITLE
 Modals attached to body

### ISSUE THREAD

**Issue by afc163** [react-component/dialog#48]
Hi, currently Modals are attached to the body, which is an issue if you do serverside rendering. Wouldn't it be a better approach to use or imitate https://github.com/cloudflare/react-gateway, in that you choose a destination inside your app component (which works great for SSR)?

---

Move from https://github.com/ant-design/ant-design/issues/3731 by @bkniffler

**Comment by eternalsky** [comment]
similar case, Can Modal provide getContainer config to support a custom container instead of just using a div (which can not be modified) attached to body?
