### ISSUE TITLE
type has no default export

### ISSUE THREAD

**Issue by KimSchneider** [react-component/dialog#52]
Hi,

I am using version 6.5.7 in a TypeScript project. The compiler throws an error

```
ERROR in [at-loader] node_modules\rc-dialog\lib\DialogWrap.d.ts:2:8
    TS1192: Module '"D:/dev/SEFrontend/report-editor/node_modules/@types/react/index"' has no default export.
```

And the usage as

`import Dialog from 'rc-dialog'`

results in errors, too. createElement receives null as type, which does not work.

Using it this style

`const Dialog = require('rc-dialog')`

works, but does not remove the first compiler error.

**Comment by yesmeck** [comment]
Set `allowSyntheticDefaultImports` to `true`.
