### ISSUE TITLE
Implement getModalContainer

### ISSUE THREAD

**Issue by bkniffler** [react-component/dialog#53]
As suggested in https://github.com/react-component/dialog/issues/48 by @eternalsky, but I figure its still something different than having a gateway (which is especially useful in SSR scenarios since no direct dom interaction is taking place). 

I think that would be pretty useful if, additionally to my suggestion and in line with other rc components like tooltip (https://ant.design/components/tooltip/), getModalContainer would be implemented so we can attach to whatever dom element we need through querySelection or getElementById.

**Comment by yesmeck** [comment]
https://github.com/react-component/dialog/commit/1dc1c5523eab46e4957c6a9461699efedc7c2aca
