### ISSUE TITLE
Disable cancel button

### ISSUE THREAD

**Issue by kud** [react-component/dialog#55]
Sometimes we want a modal but with just one action.

It should be great to be able to disable "cancel" button.

**Comment by paranoidjk** [comment]
what do you mean about  "cancel" button ?  It's the close icon  at the top-right corner ？

`props.closeable = {false}`
https://github.com/react-component/dialog#api

**Comment by kud** [comment]
No, you've got "ok" and "cancel" buttons in bottom-right corner. 

I disabled it in CSS by adding display: none on it, but i'm sure we could do better.

**Comment by paranoidjk** [comment]
@kud There is no button like you said http://react-component.github.io/dialog/. Please give use your demo code.

**Comment by kud** [comment]
<img width="207" alt="image" src="https://cloud.githubusercontent.com/assets/655838/25120192/644cd36a-241d-11e7-896f-3c043ed73f9d.png">

You've got two buttons. I would have just one.

**Comment by paranoidjk** [comment]
can't you just spend some time take a look at demo code and api doc ?
https://github.com/react-component/dialog/blob/master/examples/bootstrap.tsx#L44

**Comment by kud** [comment]
My bad. Thank you for your time.
