### ISSUE TITLE
html should set overflow:hidden, when dialog is visible

### ISSUE THREAD

**Issue by fengsx** [react-component/dialog#57]
做单页应用的时候，不想切页面时候出现滚动条来回跳。所以就参考了[这一篇文章](http://www.zhangxinxu.com/wordpress/2015/01/css-page-scrollbar-toggle-center-no-jumping/
)，设置了<html/>的样式为overflow:scroll。

而这个样式，会导致dialog展示时，出现双滚动条

**Comment by yesmeck** [comment]
没看懂到底是要 hidden 还是 scroll，提供个在线 demo 吧。
