### ISSUE TITLE
"Focus Trap" holding shift not working

### ISSUE THREAD

**Issue by lipedeitos** [react-component/dialog#63]
Hi, guys!

I am working with rc-components and they'r are suiting my needs perfectly.
Yesterday i need to mantain the focus in my dialog but i'v noticed that holding shift was making the focus leave the dialog and going to the application behing.

I thought could be something in my components but the online examples are doing the same:
http://react-component.github.io/dialog/examples/ant-design.html

This is the code that controls the shift key in **dialog.tsx**:
```
onKeyDown = (e) => {
  const props = this.props;
  if (props.keyboard && e.keyCode === KeyCode.ESC) {
      this.close(e);
  }
    // keep focus inside dialog
  if (props.visible) {
    if (e.keyCode === KeyCode.TAB) {
      const activeElement = document.activeElement;
      const dialogRoot = this.refs.wrap;
      const sentinel = this.refs.sentinel;
      if (e.shiftKey) {
        if (activeElement === dialogRoot) {
            sentinel.focus();
        }
      } else if (activeElement === this.refs.sentinel) {
          dialogRoot.focus();
      }
    }
  }
}
```
 What happens is that when you'r on the first focusable element in the dialog ex.: `<button>Close</button>` and press shift+tab, the focus get out of the dialog, because the activeElement is the button and its different than dialogRoot, so it never hits the ` if (activeElement === dialogRoot)`.

The only way this `if (activeElement === dialogRoot)` works is when you focus the dialog clicking on the background.

The simple workaround i'v found was to change the `tabIndex={-1}` of the div in render to `tabIndex={0}`. I don't know if it was set -1 because of something else, but changing to 0 works perfectly. 
I'v tested on Chrome, Mozilla and IE 11.

**Comment by Anthony-YY** [comment]
According to ARIA's suggestion, focus should be trapped inside dialog. Hope this will be fix soon.
