### ISSUE TITLE
support onOpen callback

### ISSUE THREAD

**Issue by farzer** [react-component/dialog#69]

**Comment by yesmeck** [comment]
感觉用处不大，open 的时候你是知道的。

**Comment by farzer** [comment]
这个我觉得还是有点必要吧，就比如需要监听modal打开的时候进行一些动作，这样库本身做的话就不用再额外增加一层去封装了。就比如bootstrap的modal可以监听`show.bs.modal`, `hide.bs.modal`一样

**Comment by yesmeck** [comment]
举个实际的例子吧，我看看有没有必要加。

**Comment by farzer** [comment]
~~modal使用的部分抽成公共业务， 其他组件调用这个业务只要调用打开就好了，其他的交由这个公共业务处理~~

业务场景：每次打开`dialog`的时候，需要进行远程请求数据

```
@inject('modal')  // mobx-react inject
class ModalWrap extends React.Component {
  render() {
    const { modal } = this.props
    return (
      <Dialog visible={modal.visible}>
        // other....
      </Dialog>
    )
  }
}

class Home extends React.Component {
  handleClick = () => {
    // 一些行为改变 `modal.visible` 为 true
  }
  render() {
    return (
      <>
        <Button onClick={this.handleClick}>Open Modal</Button>
        <ModalWrap />
      <>
    )
  }
}
```

没有`onOpen`类似的props会在`Home`做数据请求或者在`ModalWrap`的`componentWillReceiveProps`中做数据请求，或者是用了`event-proxy`之类的

如果`Dialog`提供了类似bs的事件监听就简单多了

**Comment by afc163** [comment]
你应该在 handleClick 里做相应的请求。

**Comment by farzer** [comment]
如果是这样的话，每一个ModalWrap的调用方就都需要做这个处理了，而这个业务，调用方其实是没有必要关注的

**Comment by yesmeck** [comment]
可以关注这个 https://github.com/ant-design/ant-design/issues/8494

**Comment by mengWenTao-Kobe** [comment]
> 举个实际的例子吧，我看看有没有必要加。

真的很有必要嘛。比如我每次打开modal，就要根据不同的id来请求数据回填modal里面的表单，如果有onOpen真的方便太多了，太多太多太多太多太多太多！！！！！！！！！！！！！！！！！！

**Comment by chenxiaochun** [comment]
> 

表示深深的赞同

**Comment by chenxiaochun** [comment]
> > 举个实际的例子吧，我看看有没有必要加。
> 
> 真的很有必要嘛。比如我每次打开modal，就要根据不同的id来请求数据回填modal里面的表单，如果有onOpen真的方便太多了，太多太多太多太多太多太多！！！！！！！！！！！！！！！！！！

表示深深的赞同

**Comment by chenxiaochun** [comment]
如果有这样一个场景：

1. 点击下面的 button 展示 modal，然后执行一下`form.submit()`方法，应该怎么处理？
2. 展示 modal 时，需要使用`form.setFieldsValue`回填表单数据，应该怎么处理？

如果有一个`onOpen`方法，岂不是会非常简单

```tsx
const FormModal = () => {
  const [form] = Form.useForm()

  return (
    <Modal open={modal.visible}>
      <Form onFinish={onFinish} form={form} {...layout}>
        ....
      </Form>
    </Modal>
  )
}

const ModalButton = () => {
  return (
    <Button
      onClick={() => {
        modal.show()
      }}
    >
      show modal
    </Button>
  )
}
```

**Comment by tylerlong** [comment]
It's already supported

```tsx
   <Modal
        afterOpenChange={(open) => {
          if (open) {
            // do something here
          }
        }}
      >
</Modal>
```
