### ISSUE TITLE
Component won't update when state.visible is true

### ISSUE THREAD

**Issue by arorayash** [react-component/dialog#74]
While using antd's Modal component, I ran into the issue where I had to display the updated props from the parent-component into the child-component,i.e., Modal.

Expected behaviour -
On setting the state in `componentWillReceiveProps` the Modal/dialog component should re-render.

Current behaviour -
The re-render is barred because of the following condition in the shouldComponentUpdate hook  -
```
  shouldComponentUpdate({ visible }) {
    return !!(this.props.visible || visible);
  }
```

**Comment by yesmeck** [comment]
Could you provide a reproduction link?

**Comment by yesmeck** [comment]
Closing since no response.
