### ISSUE TITLE
Consider removing object-assign

### ISSUE THREAD

**Issue by andriijas** [react-component/dialog#76]
it should be up to project using `dialog` to pollyfill it.

Thanks

**Comment by yesmeck** [comment]
https://github.com/react-component/react-component.github.io/issues/15

@andriijas Welcome PR

**Comment by andriijas** [comment]
Ok i will look at it. first i made script to clone all repos from react-component.

```
const fetch = require("node-fetch");
const execSync = require("child_process").execSync;

async function request(url, options = {}) {
	const response = await fetch(url, options);
	return response.json();
}

async function getCloneUrls() {
	const data = await request(
		"https://api.github.com/users/react-component/repos?page=1&per_page=100"
	);
	return data.map(repo => repo.clone_url);
}

async function main() {
	for (let url of await getCloneUrls()) {
		execSync(`git clone ${url}`);
	}
}

main();
```

**Comment by andriijas** [comment]
@yesmeck  can I also remove `create-react-class`  and use `class Dialog extends React.Component`  instead?

**Comment by yesmeck** [comment]
Hmm, how do you handle [mixin](https://github.com/react-component/dialog/blob/master/src/DialogWrap.tsx#L14) if  remove `create-react-class` ?

**Comment by andriijas** [comment]
😭   we deal with it later!
