### ISSUE TITLE
[Question] Is possible to support animation while component is un-mounting in React@16 ?

### ISSUE THREAD

**Issue by chengjianhua** [react-component/dialog#78]
https://github.com/react-component/dialog/blob/402c415d1b7af3ebca3c7cbd00ac017d3c24d3af/src/DialogWrap.tsx#L42-L56

Before the React@16, this library use `React.unstable_renderSubtreeIntoContainer` to render modal, so the unmount of modal is controlled by library. So it's able to render the **leave** animation while component is unmounted and remove the container after animation finished.

If using 16, the modal node is nested in only root tree of react application. If modal is unmounted then the content (children) of modal is also unmounted. This just behaves like the normal nested node in tree. Do you have any idea about solving this ?

I think the feature that processing leaving animation before modal is unmounted is awesome, because sometimes we really need to destroy the modal according some state changes. But this feature is so awesome that I don't want to lose it.

Thank you for your great works 🎉

**Comment by yesmeck** [comment]
It's not possible since the limitation of `Portal`. If you want unmount modal after close, try `destroyOnModal`.

**Comment by chengjianhua** [comment]
@yesmeck Thanks ~

Actually I read the docs carefully, I know the limitation by tested it myself and `destroyOnModal` is useless for me. I just hope that there is any magic I don't know is able to solve this. 😅
