### ISSUE TITLE
[Request] Add a forceRender={Boolean} attribute

### ISSUE THREAD

**Issue by tim-soft** [react-component/dialog#79]
Sometimes it is really useful to pre-render modal content, especially if data needs fetched or modal content render bottlenecks animations. 

Is it possible to add a `forceRender={Boolean}` prop like in Collapse Panel?

**Comment by yesmeck** [comment]
Could you send a PR?

**Comment by yesmeck** [comment]
Related https://github.com/ant-design/ant-design/issues/8684

**Comment by tim-soft** [comment]
@yesmeck definitely, I'll try to put something together here shortly

**Comment by afc163** [comment]
Try `destroyOnClose`
