### ISSUE TITLE
rc-dialog with typescript

### ISSUE THREAD

**Issue by baudo2048** [react-component/dialog#87]
Can I use rc-dialog component in typescript project?

I've create a file index.tsx as follow:

```
import * as React from "react"
import * as ReactDOM from "react-dom"
import {Dialog} from "rc-dialog"


ReactDOM.render(<Dialog />, document.getElementById('example'))
```

but I get the following error:

[ts] Module '"c:/Users/giuseppe.baudo/lab/work/testRcComps/node_modules/rc-dialog/lib/DialogWrap"' has no exported member 'Dialog'.

thks
baudo2048

**Comment by yesmeck** [comment]
`import Dialog from "rc-dialog"`
